language: python
python:
- 3.4.3
- 3.5.0
services:
- postgresql
- memcached
env:
- DJANGO=1.8.5
- DJANGO=1.8.6
before_install:
- export DJANGO_SETTINGS_MODULE=chirper.travis-settings
- export PYTHONPATH=$HOME/builds/jeffnb/chirper
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
- pip install psycopg2 --quiet
before_script:
- psql -c "CREATE DATABASE chirper;" -U postgres
- python manage.py migrate
script:
- coverage run --source='.' manage.py test users chirp api
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    - secure: "fCLmO/j1ZrQK3xM3hmgCu5i4adiiOUr0V73oDeA78eV93qrzEw+gzV5dFnDIq8COJDAXpKG/hcU9Wn2PlM8+x79IUHvloFVpvZ+EbcX3fS1dGxtItyn9OBrmhY9FLfmzK/x+KQh53WegGTt2j/3jkw9dmKxwX4V17KjeYjxUILj6ZV5sNelvWvCcDlX8016Zt8L96xya/3Zny8nLb8moyvRV7MXJ4mjFo2zQ8ckRtC2fRypgyDnMext/Gho0Hfiaa4Ovd5m59KEATLnw3VgGi5nio4zWwQz080O1nPc9ByIK3iYhlAvA7n7SO8XE/r8PJVwFGEvL1kzaj8g4pmQ+T325YcXiZv0xCxw8uRhDSrUwZwETw85jNd0yxge2SuUq+Vg1UzzqiIp3Gjt/npvPBbSCYDA+IlSAUr98dLG9AKRi5cJCC2ERe/YN1p0Dgem5DgqGOlfKmJgMzMU/48HuuxGTKWhy3o62m/OlltbKfa9M+0T2ikcx64bHzEPKJbdPCqZ1zKzoRtRDmiikmaBik01S6aps26uiC6IUxP7vO3M/pjHetF8p8XuUfS0ZYXAy9mCkXIzXipvJ+NB9ButUMJQvKM8mSjCEP7r5qGTXjJ2D0lua2EN0fqJixaOgsDhfJ1auk0xoFOB4X7DmQ+RGS3VIAFswvKh1SSbCaXwxGg0="
  app: salty-savannah-2651
