language: python
python:
- 3.4.3
- 3.5.0
services:
- postgresql
- memcached
env:
- DJANGO=1.8.5
- DJANGO=1.8.6
before_install:
- export DJANGO_SETTINGS_MODULE=chirper.travis-settings
- export PYTHONPATH=$HOME/builds/jeffnb/chirper
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
- pip install psycopg2 --quiet
before_script:
- psql -c "CREATE DATABASE chirper;" -U postgres
- python manage.py migrate
script:
- coverage run --source='.' manage.py test users chirp api
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: P+spc0kukab7Wph5uUvOuQpErEtKkQkAEh4dUsD5ilC3vf8NjIU13r58eGu4j9lHBW8aocbGlgmX7tQOiQ3acCdZbXU7pSPAFZ0XJUpnz0VA8WlviY1S7QVswa82f03u6hAGzhIu+kbX8VRsxJu1J/kaIAze3aAs7TJo3KzbzY6QIu2QC2ZzRfjGBaBwjMji4p90dAOUBp88O6sjsjyJn1wudrM0EfOMMkyWjDfoh7Z/2IFrV8zTqNacEo3NKg0AZ0V9my83165gGGYPRdDXGS/rnezUJvgOLJ2TdQrjXj+XBF2NvN+1/eiAegYBXL9aj+92ZmKgwe9PYMgp3ULBh+EDtkfs3jPiOZej04T3QHdjdtwsob1pGXH7CgopRd7vSKjuA0B9BVudcq4GBRk0Gj8I6URBUQ7nT2j+Ct8LktRFCXIpp94JN6/9/6mai8JS2CymTO5u78smzdxCWRhCwnhbT5sINlwaAGLKYIKSQTCWXQXMb6wByu1N6teJhrwhPgltiIMOEYM8x1RGlSZzUVKSTabUFWOccUuWjnJGTkMunT1axc4qqsKNL81HtV0pXIF1K2fLiHI1RHFxrKhmE13mx6G9RnddK58SyDwfOgtdhsWE/hpIwXMN3bSjkRioOWOwiybsruvlzwGGH8rVeCNmtdGsimc1isu1gYd5IsI=
  app: salty-savannah-2651
  run: "python manage.py migrate"