language: python
python:
- 3.4.3
- 3.5.0
services:
- postgresql
- memcached
env:
- DJANGO=1.8.5
- DJANGO=1.8.6
before_install:
- export DJANGO_SETTINGS_MODULE=chirper.travis-settings
- export PYTHONPATH=$HOME/builds/jeffnb/chirper
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
- pip install psycopg2 --quiet
before_script:
- psql -c "CREATE DATABASE chirper;" -U postgres
- python manage.py migrate
script:
- coverage run --source='.' manage.py test users chirp api
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    - secure: bcnZnV4q+mPkG9k2WjzUgcyR1PHRPIkQsp6CKzRTvQiDTQsoKs3Uf64Y6FYg08u7Z8w+XM0WJ9e7WYi+X/siRopChyhHtNhHDdwLNaM1lwwEzsO4fBb26JLd1vK3kjwA/Ep2aIcjsxaAEsctRvUDB5fv6yE81JeS8qJtBjuoLWUtAJOgLIFfD+Tirk9IJ2mOxL67W0+Sn/bb5S7jWF/wqm4H0tGtf16sjxYcxwFSsxBI/iVfxbQtGjNmlGfflnIAahFiDbuQu6i9YGmoKRUszSPrEK+7Xqm5mBXD+ZpcgFQHvvh9ZrsRVuwPdPDTssMnIMkORIQ4cB43R934a9kkT84jXTPhS0jPyRp6P1ahYwuwkNUSHmn9NoriT0Z5jh7uYBLjBJjhkLNcD7ECFQcKlOJUYVnQ4lpVTBX471BuMvw1bxS4D5VcWmGU4xT3/vE5/eRly8J4KrKo5+WkyAqmnVKriE768rKDoW7xYGwiZ5Al/Vl1yK+I3TwI1AmhezftVfllkz3SHJgHxvARFvAII2xbM+1fixUXqbo5SE7Rz0BHrTT/jzeNsSIgOg4PxP1e/j1h5tcCX8GGcbLEkUl0iPm4fWubNOowk5GYsooBwh2kuF6KtOS4G908fhovOk1sLD59nzO1cBa2NrsGJ+i1PSzsgFpYa+7mvuHr6v7ByKQ=
  app: salty-savannah-2651
